package day39_b_exception.learning;

public class FourthTry {
}
